#!/bin/bash
set -e

# hadoop related path
HADOOP_PATH="/usr/local/hadoop/"
HADOOP_CONF=$(echo -n "$HADOOP_PATH/etc/hadoop/")
HADOOP_SLAVES_FILE=$(echo $HADOOP_CONF/slaves)
HADOOP_INIT_SCRIPT="/root/hadup/init/hadoop"
HADOOP_RUN_USER="hadmin"

rm $HADOOP_SLAVES_FILE
#update each datanode /etc/hostname
#update each datanode /etc/hosts
#reboot every datanode or run hostname command
#fixme not just touh me
#update $HADOOP_SLAVES_FILE namenode only
chown -R $HADOOP_RUN_USER:$HADOOP_RUN_USER $HADOOP_PATH

# format hdfs
su - $HADOOP_RUN_USER -c "$HADOOP_PATH/bin/hadoop namenode -format"
sleep 5

## install init script namenode only
cp $HADOOP_INIT_SCRIPT /etc/init.d/
echo "/etc/init.d/hadoop start"

#echo "jps on master"
#su - $HADOOP_RUN_USER -c jps
#echo "jps on slaves"
#drbl-doit -h $DHOSTS "su - $HADOOP_RUN_USER -c jps"
#
## run example
#echo "run hadoop example"
#echo "su - $HADOOP_RUN_USER -c $HADOOP_PATH/bin/hadoop jar /usr/local/hadoop/share/hadoop/mapreduce/hadoop-mapreduce-examples-2.3.0.jar pi 1 1"
#su - $HADOOP_RUN_USER -c "$HADOOP_PATH/bin/hadoop jar /usr/local/hadoop/share/hadoop/mapreduce/hadoop-mapreduce-examples-2.3.0.jar pi 1 1"
#
#echo "su - $HADOOP_RUN_USER -c $HADOOP_PATH/bin/hadoop jar /usr/local/hadoop/share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-2.3.0.jar  TestDFSIO -write -nrFiles 2 -size 2MB"
#su - $HADOOP_RUN_USER -c "$HADOOP_PATH/bin/hadoop jar /usr/local/hadoop/share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-2.3.0.jar  TestDFSIO -write -nrFiles 2 -size 2MB"
#
#echo "enjoy hadoop, su to hduser to run all hadoop related commands."
