#!/bin/bash
# post run for ezilla datanode of hadoop cluster
# 1. update hostname
# 4. report ip and hostname to namenode

set -e

datanode_flag="/etc/datanode"
update_datanode_cmd="/root/ezilla-hadoop-namenode-postrun"

if [ -f $datanode_flag ];then
    exit
fi

# add -f option ?
logger "datanode post run"
list_of_all_slaves="/root/new_slaves/"
namenode_ip=$(cat /etc/namenode)
netdev="eth0"
datanode_ip=$(ifconfig $netdev | grep 'inet addr' | awk '{print $2}' | sed s/addr://)

suffix=$(echo $datanode_ip | sed "s/.*\.//g")

new_host_name="datanode$suffix"
logger "$datanode_ip $new_host_name"

# 1. update hostname
hostname $new_host_name
logger "set hostname to $new_host_name"
echo $new_host_name > /etc/hostname
echo "$datanode_ip  $new_host_name" > $datanode_flag
chmod 400 $datanode_flag

#4. report ip and hostname to namenode
logger "scp data to $list_of_all_slaves "
#scp $datanode_flag $namenode_ip:$list_of_all_slaves/$new_host_name

while true
do
ret=$(ssh $namenode_ip $update_datanode_cmd)
if [ "X$ret" -eq "Xrunning" ];then
    sleep 15
elif ["X$ret" -eq "XOk"]; then
    logger "add to hadoop $ret"
    break
else
    logger "$ret"
    echo $ret
    break
fi
done
