#! /bin/sh
### BEGIN INIT INFO
# Provides:          hadoop-common
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start hadoop at boot time
# Description:       Enable hadoop cluster services at boot time
### END INIT INFO

HADOOP_RUN_USER=hadmin
HADOOP_PATH=/usr/local/hadoop

[ -f /etc/datanode_status ] || exit 

case "$1" in
  start)
    echo "Starting hadoop common"
    su - $HADOOP_RUN_USER -c "$HADOOP_PATH/sbin/yarn-daemon.sh start nodemanager"
    su - $HADOOP_RUN_USER -c "$HADOOP_PATH/sbin/hadoop-daemon.sh start datanode"
    sleep 5
    jps
    ;;
  stop)
    echo "Stopping common"
    su - $HADOOP_RUN_USER -c "$HADOOP_PATH/sbin/hadoop-daemon.sh stop datanode"
    su - $HADOOP_RUN_USER -c "$HADOOP_PATH/sbin/yarn-daemon.sh stop nodemanager"
    sleep 5
    jps
    ;;
  *)
    echo "Usage: /etc/init.d/hadoop {start|stop}"
    exit 1
    ;;
esac

exit 0

