#!/bin/bash
# post run for ezilla datanode of hadoop cluster
# 1. update hostname
# 4. report ip and hostname to namenode

touch /etc/datanode_status
dn_status=$(cat /etc/datanode_status)
if [ "X$dn_status" == "XOk" ];then
    exit
fi

datanode_flag="/etc/datanode"
update_datanode_cmd="/opt/ezilla-hadoop/ezilla-hadoop-namenode-postrun"

set -e

# add -f option ?
logger "datanode post run"
namenode_ip=$(cat /etc/namenode)
netdev="eth0"
datanode_ip=$(ifconfig $netdev | grep 'inet addr' | awk '{print $2}' | sed s/addr://)

suffix=$(echo $datanode_ip | sed "s/.*\.//g")

new_host_name="datanode$suffix"
logger "$datanode_ip $new_host_name"

# 1. update hostname
hostname $new_host_name
logger "set hostname to $new_host_name"
echo $new_host_name > /etc/hostname
echo "$datanode_ip  $new_host_name" > $datanode_flag
chmod 400 $datanode_flag

# 2. remove slaves
set +e
rm /usr/local/hadoop/etc/hadoop/slaves
set -e

while true
do
ret=$(ssh $namenode_ip $update_datanode_cmd $datanode_ip $new_host_name)
if [ "X$ret" == "Xrunning" ];then
    sleep 15
elif [ "X$ret" == "XOk" ]; then
    logger "add to hadoop $ret"
    echo $ret > /etc/datanode_status
    /etc/init.d/hadoop_dn start
    break
else
    logger "$ret"
    echo $ret
    break
fi
done
